/*
 * This task is a bit harder than the previous two.
 * Feel free to change the E3SLinqProvider and any other classes if needed.
 * Possibly, after these changes you will need to rewrite existing tests to make them work again =).
 *
 * The task: implement support of && operator for IQueryable. The final request generated by FTSRequestGenerator, should
 * imply the following rules: https://kb.epam.com/display/EPME3SDEV/Telescope+public+REST+for+data#TelescopepublicRESTfordata-FTSRequestSyntax
 */

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Net.Http;
using System.Text.RegularExpressions;
using Expressions.Task3.E3SQueryProvider.Models.Entities;
using Expressions.Task3.E3SQueryProvider.Services;
using Xunit;

namespace Expressions.Task3.E3SQueryProvider.Test
{
    public class E3SAndOperatorSupportTests
    {
        #region SubTask 3: AND operator support

        [Fact]
        public void TestAndQueryable()
        {
            var translator = new ExpressionToFtsRequestTranslator();
            Expression<Func<IQueryable<EmployeeEntity>, IQueryable<EmployeeEntity>>> expression
                = query => query.Where(e => e.Workstation == "EPRUIZHW006" && e.Manager.StartsWith("John"));

            var translated = translator.Translate(expression);

            Assert.Equal("Workstation:(EPRUIZHW006)ANDManager:(John*)", translated);

            var ftsRequestGenerator = new FtsRequestGenerator("http://someaddress.com");

            var resultRequest = ftsRequestGenerator.GenerateRequestUrl<EmployeeEntity>(translated);

            //JB: I decided to check the query generated by FtsRequestGenerator, not invoking E3SSearchService, as I don't have the proper address to call E3S API and the FtsRequestGenerator is invoked within that. 
            //I think this is the main point of this test, but please correct me if I'm wrong.
            Assert.Equal(expectedQuery, resultRequest.Query);
           
            /*
             * The expression above should be converted to the following FTSQueryRequest and then serialized inside FTSRequestGenerator:
             * "statements": [
                { "query":"Workstation:(EPRUIZHW006)"},
                { "query":"Manager:(John*)"}
                // Operator between queries is AND, in other words result set will fit to both statements above
              ],
             */
        }


        // It contains the following:
        //            @"{
        //    ""statements"": [
        //        {
        //            ""query"": ""Workstation:(EPRUIZHW006)""
        //        },
        //        {
        //            ""query"": ""Manager:(John*)""
        //        }
        //    ],
        //    ""filters"": null,
        //    ""sorting"": null,
        //    ""start"": 0,
        //    ""limit"": 10
        //}";
        private const string expectedQuery = @"?metaType=meta%3Apeople-suite%3Apeople-api%3Acom.epam.e3s.app.people.api.data.EmployeeEntity&query=%7B%22statements%22%3A%5B%7B%22query%22%3A%22Workstation%3A(EPRUIZHW006)%22%7D,%7B%22query%22%3A%22Manager%3A(John*)%22%7D%5D,%22filters%22%3Anull,%22sorting%22%3Anull,%22start%22%3A0,%22limit%22%3A10%7D";
        

        #endregion
    }
}
